apiVersion: v1
kind: Service
metadata:
  name: simple-node-app
spec:
  type: ClusterIP
  selector:
    app: simple-node-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
